typography_spectrum: 1
color:
  saturation: 0.6648745
  lightness: 0.147311
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#955A0E'
    - '#707070'
    - '#B28556'
    - '#CFB497'
  rhythmicContrast: 0.8800644
layout_spectrum: 0.7164286
author:
  name: afc law
  email: office@afc-pa.com
  url: afclaw.info
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e2dcf90-caed-4738-9c41-19fff2d7b9b1.jpg
name: afc law
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e11312ba-d7fa-4025-a26e-2b57f4f27121.png
title: a real estate law firm
description: legal solutions that make business sense
